# Generated by Django 5.0.3 on 2024-03-08 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='url',
            new_name='slug',
        ),
    ]
