# Generated by Django 5.0.3 on 2024-03-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_author_summary_author_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='work',
            field=models.CharField(default='Journalist', max_length=100),
            preserve_default=False,
        ),
    ]
